data:
    orig_data_resolution: 240
    orig_num_slices: 155
    resolution: 128
    num_slices: 64
    n_samples: 500
    modalities:
    - flair
    - t1ce
    binarize: true
    npy_path: ./data/brats_3d_dataset.npy
    root_path: '../common_data/RSNA_ASNR_MICCAI_BraTS2021_TrainingData_16July2021'
callbacks:
    checkpoint:
        log_path: ./logs
        ckpt_path: ./checkpoints
        save_ckpt_at_every: 50
        save_log_at_every: 1
models:
    unet:
        in_channels: 8
        out_channels: 8
        learning_rate: 0.00001
        T: 1000
        resolution: 128
        num_channels: 128
        channel_mult: 
        - 1
        - 2
        - 2
        - 4
        temb_dim: 128
        temb_dim_mult: 4
        attn: 
        - false
        - false
        - true
        - false
        num_res_blocks: 2
        beta_schedule: cosine
    autoencoder:
        in_channels: 2
        out_channels: 2 
        n_embed: 8192
        embed_dim: 2
        z_channels: 4
        z_double: false 
        pemb_dim: 128
        T: 64
        num_channels: 128
        channels_mult:
        - 1
        - 2
        - 4
        num_res_blocks: 2
        attn: []
        learning_rate: 0.00001
        loss:
            disc_start: 11
            codebook_weight: 1.0
            pixel_weight: 1.0
            perceptual_weight: 1.0
            disc_weight: 1.0
            cos_weight: 0.0
            disc_input_channels: 2
            disc_channels: 64
            disc_num_layers: 3
            disc_factor: 1.0
    

